### ISSUE TITLE
Running main.py: no module name 'idlelib'

### ISSUE THREAD

**Issue by Duality4Y** [blueyesess/WaveDromGen#2]
System:
$ lsb_release -a
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

python:
```
Python 3.10.12
```

how to reproduce:
run a linux machine
clone this repository and enter it:
 $ git clone https://github.com/blueyesess/WaveDromGen
 $ cd WaveDromGen
install dependencies in requirements.txt like so:
 $ pip install -r requirements.txt
run main.py:
 $ python main.py

result:
```
Traceback (most recent call last):
  File "/home/robert/Documents/Code/WaveDromGen/main.py", line 1, in <module>
    from WaveDromGen.WaveDromUI import WaveDromUI
  File "/home/robert/Documents/Code/WaveDromGen/WaveDromGen/__init__.py", line 1, in <module>
    import WaveDromGen.WaveDromUI as WaveDromUI
  File "/home/robert/Documents/Code/WaveDromGen/WaveDromGen/WaveDromUI.py", line 16, in <module>
    from WaveDromGen.WaveNote import WaveNote
  File "/home/robert/Documents/Code/WaveDromGen/WaveDromGen/WaveNote.py", line 8, in <module>
    import idlelib.colorizer as idc
ModuleNotFoundError: No module named 'idlelib'
```

**Comment by Duality4Y** [comment]
has additional dependency on Linux platforms it needs idle3 installed.
On my platform (Ubuntu):
apt install idle3
